storage:
  vars:
    bucket_name: neon-dev-storage-eu-west-1
    bucket_region: eu-west-1
    console_mgmt_base_url: http://neon-internal-api.aws.neon.build
    broker_endpoint: http://storage-broker-lb.zeta.eu-west-1.internal.aws.neon.build:50051
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      metric_collection_endpoint: http://neon-internal-api.aws.neon.build/billing/api/v1/usage_events
      metric_collection_interval: 10min
      tenant_config:
        eviction_policy:
          kind: "LayerAccessThreshold"
          period: "20m"
          threshold: "20m"
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "pageserver/v1"
    safekeeper_s3_prefix: safekeeper/v1/wal
    hostname_suffix: ""
    remote_user: ssm-user
    ansible_aws_ssm_region: eu-west-1
    ansible_aws_ssm_bucket_name: neon-dev-storage-eu-west-1
    console_region_id: aws-eu-west-1
    sentry_environment: staging

  children:
    pageservers:
      hosts:
        pageserver-0.eu-west-1.aws.neon.build:
          ansible_host: i-01d496c5041c7f34c

    safekeepers:
      hosts:
        safekeeper-0.eu-west-1.aws.neon.build:
          ansible_host: i-05226ef85722831bf
        safekeeper-1.eu-west-1.aws.neon.build:
          ansible_host: i-06969ee1bf2958bfc
        safekeeper-2.eu-west-1.aws.neon.build:
          ansible_host: i-087892e9625984a0b
